// Generates src/lib/symbols/data.ts from the svg-control-descriptions package.
//
//   node scripts/build-symbols.mjs
//
// The output is committed, so the app has no runtime dependency on that package and the
// ~70 glyphs are inlined in the bundle rather than being ~70 files to precache.
//
// Only IOF column D is taken — the feature column, the one that names a thing on the
// ground. Columns C, E, F and G are modifiers and directions ("North-east side"), which
// are not what "know your symbols" means and would flood the pool with near-identical
// glyphs. Category 6 ("Special item") is dropped too: both entries share one name and it
// has no fixed meaning to be quizzed on.
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const DIR = 'node_modules/svg-control-descriptions/symbols';
const lang = JSON.parse(readFileSync(join(DIR, 'lang.json'), 'utf8'));

const CATEGORIES = {
  1: 'landform',
  2: 'rock',
  3: 'water',
  4: 'vegetation',
  5: 'man-made',
};

/** Strip the wrapper and hand the colour over to CSS, so one glyph works on any ground. */
function inner(svg) {
  const body = svg.replace(/^[\s\S]*?<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '');
  return body
    .replace(/stroke="black"/g, 'stroke="currentColor"')
    .replace(/fill="black"/g, 'fill="currentColor"')
    .trim();
}

const seen = new Set();
const symbols = [];

for (const [id, meta] of Object.entries(lang)) {
  if (meta.kind !== 'D') continue;
  const category = CATEGORIES[Number(id.split('.')[0])];
  if (!category) continue;
  const name = meta.names?.en;
  if (!name || seen.has(name)) continue;
  seen.add(name);
  symbols.push({ id, name, category, svg: inner(readFileSync(join(DIR, `${id}.svg`), 'utf8')) });
}

// Sorted by IOF number so the generated file has a stable order: an unstable one would
// change every golden hash on a rebuild for no reason.
const key = (id) => id.split('.').map(Number);
symbols.sort((a, b) => key(a.id)[0] - key(b.id)[0] || key(a.id)[1] - key(b.id)[1]);

const out = `// GENERATED by scripts/build-symbols.mjs — do not edit.
// Source: svg-control-descriptions (IOF column D), extracted from Purple Pen.
// See README for the licence note.

export interface SymbolDef {
  /** IOF control-description number, e.g. "1.10". */
  readonly id: string;
  readonly name: string;
  readonly category: SymbolCategory;
  /** Inner SVG for a "-100 -100 200 200" viewBox; colour comes from currentColor. */
  readonly svg: string;
}

export type SymbolCategory = ${Object.values(CATEGORIES).map((c) => `'${c}'`).join(' | ')};

export const SYMBOLS: readonly SymbolDef[] = ${JSON.stringify(symbols, null, 2)};
`;

writeFileSync('src/lib/symbols/data.ts', out);
console.log(`wrote src/lib/symbols/data.ts — ${symbols.length} symbols`);
for (const c of Object.values(CATEGORIES)) {
  console.log(`  ${c}: ${symbols.filter((s) => s.category === c).length}`);
}
